services:
  mongo:
    image: 'mongo:7.0.2'
    ports:
      - '27017:27017'
    volumes:
      - '${MONGO_DIR}:/data/db'
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      TZ: '${TZ}'
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
  mongo-express:
    image: 'mongo-express:1.0.2-20'
    ports:
      - '8083:8081'
    depends_on:
      - mongo
    environment:
      TZ: '${TZ}'
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGO_USER}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGO_PASSWORD}'
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/'
      ME_CONFIG_BASICAUTH_USERNAME: '${MONGO_USER}'
      ME_CONFIG_BASICAUTH_PASSWORD: '${MONGO_PASSWORD}'
    entrypoint:
      - sh
      - '-c'
      - sleep 10s && tini -- /docker-entrypoint.sh mongo-express
  backend:
    build:
      context: ./backend
    ports:
      - '8081:8080'
    depends_on:
      - mongo
    environment:
      TZ: '${TZ}'
      MONGO_HOST: mongo
      MONGO_USER: '${MONGO_USER}'
      MONGO_PASSWORD: '${MONGO_PASSWORD}'
  keycloak-db:
    image: 'postgres:14.4'
    volumes:
      - '${KC_DB_DIR}:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: '${KC_DB_PASSWORD}'
      POSTGRES_DB: '${KC_DB_NAME}'
      POSTGRES_USER: '${KC_DB_USER}'
      TZ: '${TZ}'
      PGTZ: '${TZ}'
  keycloak:
    build:
      context: ./auth/keycloak
    ports:
      - '8080:8080'
    volumes:
      - '${KC_DIR}:/opt/keycloak/data'
    environment:
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: '${KC_DB_NAME}'
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: '${KC_DB_USER}'
      KC_DB_PASSWORD: '${KC_DB_PASSWORD}'
      KEYCLOAK_ADMIN: '${KC_ADMIN}'
      KEYCLOAK_ADMIN_PASSWORD: '${KC_ADMIN_PASSWORD}'
      TZ: '${TZ}'
    depends_on:
      - keycloak-db
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
  keycloak-conf:
    build: 
      context: ./auth/keycloak-conf
    environment:
      KEYCLOAK_URL: 'http://keycloak:8080/'
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      KEYCLOAK_USER: '${KC_ADMIN}'
      KEYCLOAK_PASSWORD: '${KC_ADMIN_PASSWORD}'
      IMPORT_FILES_LOCATIONS: /config/standalone.json
      IMPORT_MANAGED_GROUP: no-delete
      IMPORT_MANAGED_ROLE: no-delete
      IMPORT_MANAGED_COMPONENT: no-delete
      IMPORT_MANAGED_SUBCOMPONENT: no-delete
      IMPORT_MANAGED_IDENTITYPROVIDER: no-delete
      IMPORT_MANAGED_IDENTITYPROVIDERMAPPER: no-delete
      IMPORT_VARSUBSTITUTION_ENABLED: true
      TZ: '${TZ}'
    depends_on:
      - keycloak
  plugin:
    build:
      context: ./plugin
      args:
        URL: https://localhost:8443/latest
    environment:
      TZ: '${TZ}'
    ports:
      - '8443:443'